### ISSUE TITLE
Category color settings disappear after I click save

### ISSUE THREAD

**Issue by carie95** [the-events-calendar/the-events-calendar-category-colors#168]
![Schermafbeelding 2024-10-15 103249](https://github.com/user-attachments/assets/cecaf866-e55f-4db3-9633-b7fce3e61397)

Hello! I'm very new to Wordpress, but most of the times I figure things out on my own with some patience. I use the free version of The Events Calendar and downloaded the Category Colors for my calendar. My display looks weird, I don't know why? When I choose the colors for the categories, and press "save", everything dissapears? What do I do wrong? Do I miss something? Does it only works on the paid version? If somebody could help me, I'm very thankful. 

Kind regards, cariena95

**Comment by PhilippKilian** [comment]
I have the same issue.

I'm using the plugins since 2022 and with the last update I think, the save button doesn't work right anymore.
Any changes I made (edit or add) isn't persisted stored, which leads to a broken plugin, which works with an already existing configuration, but cannot be adjusted anymore.

Plugin-Version: `7.3.2`
The Events Calendar Version: `6.7.0`
Wordpress-Version: `6.6.2`
PHP-Version: `8.2`

**Comment by afragen** [comment]
It is related to the issue above and any current issue that involves saving preferences. 

This has been fixed in the `develop` branch and should be released soon.

**Comment by carie95** [comment]
Thank you for your answers!

**Comment by mlpeck-abcbs** [comment]
@afragen Thanks for the update I am having this issue as well. Any idea when the fix should be released?

**Comment by afragen** [comment]
Fixed in recent release
